export default [
  {
    location_id: 7,
    title: '台北物流中⼼',
    city: '台北市',
    address: '台北市中正區忠孝東路100號',
  },
  {
    location_id: 13,
    title: '新⽵物流中⼼',
    city: '新⽵市',
    address: '新⽵市東區光復路⼀段101號',
  },
  {
    location_id: 24,
    title: '台中物流中⼼',
    city: '台中市',
    address: '台中市⻄區⺠⽣路200號',
  },
  {
    location_id: 3,
    title: '桃園物流中⼼',
    city: '桃園市',
    address: '桃園市中壢區中央⻄路三段150號',
  },
  {
    location_id: 18,
    title: '⾼雄物流中⼼',
    city: '⾼雄市',
    address: '⾼雄市前⾦區成功⼀路82號',
  },
  {
    location_id: 9,
    title: '彰化物流中⼼',
    city: '彰化市',
    address: '彰化市中⼭路⼆段250號',
  },
  {
    location_id: 15,
    title: '嘉義物流中⼼',
    city: '嘉義市',
    address: '嘉義市東區⺠族路380號',
  },
  {
    location_id: 6,
    title: '宜蘭物流中⼼',
    city: '宜蘭市',
    address: '宜蘭市中⼭路⼆段58號',
  },
  {
    location_id: 21,
    title: '屏東物流中⼼',
    city: '屏東市',
    address: '屏東市⺠⽣路300號',
  },
  {
    location_id: 1,
    title: '花蓮物流中⼼',
    city: '花蓮市',
    address: '花蓮市國聯⼀路100號',
  },
  {
    location_id: 4,
    title: '台南物流中⼼',
    city: '台南市',
    address: '台南市安平區建平路18號',
  },
  {
    location_id: 11,
    title: '南投物流中⼼',
    city: '南投市',
    address: '南投市⾃由路67號',
  },
  {
    location_id: 23,
    title: '雲林物流中⼼',
    city: '雲林市',
    address: '雲林市中正路五段120號',
  },
  {
    location_id: 14,
    title: '基隆物流中⼼',
    city: '基隆市',
    address: '基隆市信⼀路50號',
  },
  {
    location_id: 8,
    title: '澎湖物流中⼼',
    city: '澎湖縣',
    address: '澎湖縣⾺公市中正路200號',
  },
  {
    location_id: 19,
    title: '⾦⾨物流中⼼',
    city: '⾦⾨縣',
    address: '⾦⾨縣⾦城鎮⺠⽣路90號',
  },
];
